"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
const modules=[["AI CHAT","Ask, research and create","/app/chat"],["AGENTS","Build specialized AI workers","/agents"],["FACTORIES","Turn ideas into repeatable systems","/platform"],["AUTOMATIONS","Connect work into workflows","/solutions/automation"],["KNOWLEDGE","Build your private intelligence layer","/resources/knowledge"],["MARKETPLACE","Install products and business systems","/marketplace"],["PLUGIN LAUNCHER","Launch J-ROC plugins from your workspace","/app/plugins"],["J-ROC CLI","Run approved platform commands from the web","/app/cli"]];
export default function WorkspacePage(){
 const [checking,setChecking]=useState(true); const [user,setUser]=useState<{username:string;role:string}|null>(null);
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/auth/me",{credentials:"include",cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();setUser(d);}catch{localStorage.removeItem("jroc_token");localStorage.removeItem("jroc_role");window.location.href="/login";}finally{setChecking(false);}})();},[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST",credentials:"include"}).catch(()=>{});localStorage.removeItem("jroc_token");localStorage.removeItem("jroc_role");window.location.href="/login";}
 if(checking)return <div className="workspace-shell"><main className="workspace-main"><p>AUTHENTICATING J-ROC WORKSPACE…</p></main></div>;
 return <div className="workspace-shell"><aside className="workspace-sidebar"><Link href="/" className="workspace-brand">J-ROC <span>AI</span></Link><div className="workspace-nav"><b>WORKSPACE</b>{modules.map(([x,,href])=><Link href={href} key={x}>{x}</Link>)}<b>OPERATING SYSTEM</b>{["Business OS","Creator OS","Academy","Analytics"].map(x=><a href="#" key={x}>{x}</a>)}<b>COMMAND CENTER</b><Link href="/app/plugins">PLUGIN LAUNCHER</Link><Link href="/app/cli">J-ROC CLI</Link></div><Link href="/chairman/login" className="workspace-private">CHAIRMAN ACCESS →</Link><button onClick={logout} className="workspace-private">SIGN OUT</button></aside>
 <main className="workspace-main"><header className="workspace-top"><div><span className="eyebrow">J-ROC AI WORKSPACE</span><h1>Welcome, {user?.username}.</h1></div><div className="workspace-status"><span className="signal"/> SYSTEM ONLINE · {user?.role}</div></header>
 <section className="workspace-command"><div><div className="card-kicker">AI COMMAND</div><h2>What are we building today?</h2><p>Start a conversation, launch a factory, create an agent or turn an idea into a mission.</p></div><Link className="workspace-input" href="/app/chat">Ask J-ROC anything... <span>↗</span></Link></section>
 <section className="workspace-grid">{modules.map(([t,d,href],i)=><Link href={href} className="workspace-card" key={t}><span className="card-kicker">0{i+1}</span><h3>{t}</h3><p>{d}</p><span className="card-link">OPEN →</span></Link>)}</section>
 <section className="workspace-lower"><div><div className="card-kicker">ACTIVE SYSTEMS</div><h2>Operations at a glance</h2><div className="metric-row"><span>Agents <b>—</b></span><span>Automations <b>—</b></span><span>Missions <b>—</b></span></div></div><div className="activity"><div className="card-kicker">SESSION</div><p><span className="signal"/> Authenticated as {user?.username}</p><p><span className="signal"/> Cloud workspace available</p><p><span className="signal"/> Cross-device session enabled</p></div></section></main></div>;
}