"use client";

import { useEffect, useState } from "react";

const divisions = ["Technology","AI","Entertainment","Growth","Academy","Ventures","Marketing","Sales","Operations","Finance","Research","Publishing","Media"];
const executives = [["CEO","Strategy & direction"],["COO","Operations & delivery"],["CTO","Architecture & platform"],["CFO","Financial control"],["CIO","Data & AI"],["CMO","Growth & brand"],["CSO","Security & risk"],["CLO","Legal & policy"],["CCO","Compliance"]];
const layers = [
  ["🏛","Chairman Office","Directives, approvals, overrides, emergency stop and full audit."],
  ["🧠","Triple Command Brain","Primary plans · Validator verifies · Healer recovers · Consensus decides."],
  ["🦾","Executive AI Council","Nine executives with models, tools, goals, memory and sessions."],
  ["🎯","Mission Engine","Plan → decompose → delegate → execute → validate → recover."],
  ["🧩","Universal Division Engine","Every division is the same object — added as data."],
  ["🏗","AI App Factory","Idea → architecture → database → backend → UI → AI → test → deploy."],
  ["📡","Model Gateway","Provider-independent routing, fallback, health, usage and cost."],
  ["🧬","Memory + Knowledge","Layered memory and semantic retrieval across the platform."]
];

export default function HomePage() {
  const [live, setLive] = useState("CONNECTING TO J-ROC CORE…");
  useEffect(() => {
    fetch("/api/health",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setLive("J-ROC CORE ONLINE · "+(d.platform||"J-ROC AI"))).catch(()=>setLive("J-ROC CORE DEPLOYED · ENTER THE OS TO CONNECT"));
  }, []);
  return <div className="jroc-front">
    <div className="j-grid"/><div className="j-aurora"/>
    <header className="j-nav">
      <a className="j-brand" href="#top"><span className="j-logo">JR</span><span>J-ROC <b>AI</b></span></a>
      <nav><a href="#platform">Platform</a><a href="#council">Council</a><a href="#divisions">Divisions</a><a href="#solutions">Solutions</a><a href="#entertainment">Entertainment</a></nav>
      <a className="j-btn j-ghost" href="/os">Enter J-ROC AI</a>
    </header>
    <main id="top">
      <section className="j-hero">
        <div><span className="j-eyebrow">J-ROC AI · 2026</span><h1>The AI Operating System<br/><span>The enterprise command layer.</span></h1>
          <p>Not fifty disconnected apps. One platform: an <b>Executive AI Council</b>, a <b>Triple Command Brain</b>, a persistent <b>Mission Engine</b>, a <b>Universal Division Engine</b> and an <b>AI App Factory</b> — delivered through the browser.</p>
          <div className="j-actions"><a className="j-btn" href="/os">Enter J-ROC AI →</a><a className="j-btn j-ghost" href="#platform">See the architecture</a></div>
          <div className="j-live"><i/> {live}</div>
        </div>
        <div className="j-core"><div className="j-ring r1"/><div className="j-ring r2"/><div className="j-ring r3"/><div className="j-corecenter">J-ROC<br/><b>CORE</b></div><label>EXECUTE · VERIFY · RECOVER · CONSENSUS</label></div>
      </section>
      <section className="j-stats"><div><b>13</b><small>Divisions</small></div><div><b>9</b><small>Executives</small></div><div><b>9</b><small>Command phases</small></div><div><b>15</b><small>Factory stages</small></div><div><b>6</b><small>Model providers</small></div></section>
      <section className="j-section" id="platform"><span className="j-eyebrow">THE PLATFORM</span><h2>A small number of engines,<br/>not a pile of pages.</h2><p className="j-muted">The front door is a website. Underneath it is an operating environment where AI executives, workers, missions and applications run on one Core + Runtime.</p>
        <div className="j-gridcards">{layers.map(([icon,title,text])=><article key={title}><strong>{icon}</strong><div><b>{title}</b><p>{text}</p></div></article>)}</div>
      </section>
      <section className="j-section" id="council"><span className="j-eyebrow">EXECUTIVE AI COUNCIL</span><h2>Nine executives. One Chairman.</h2><p className="j-muted">Each executive has identity, system instructions, model access, memory, tools, permissions, goals and a task queue.</p><div className="j-execs">{executives.map(([a,b])=><article key={a}><b>{a}</b><span>{b}</span></article>)}</div><div className="j-ceo"><span>🦾</span><div><b>J-ROC AI — the official AI CEO.</b><p>Coordinates the council and divisions through the model gateway while respecting Chairman approval gates.</p></div></div></section>
      <section className="j-section" id="divisions"><span className="j-eyebrow">UNIVERSAL DIVISION ENGINE</span><h2>Thirteen divisions,<br/>structurally identical.</h2><p className="j-muted">Executive, departments, workers, apps, missions, automations, knowledge, data and analytics.</p><div className="j-divisions">{divisions.map((d,i)=><article key={d}><span>{["☁","🧠","🎬","📈","🎓","🚀","📣","🤝","⚙","💰","🔬","📚","📺"][i]}</span><b>{d}</b></article>)}</div></section>
      <section className="j-section" id="solutions"><span className="j-eyebrow">SOLUTIONS</span><h2>What the platform does.</h2><div className="j-solutions">{["AI Workforce","Mission Control","AI App Factory","Automation Fabric","Marketplace","Governance"].map(x=><article key={x}><h3>{x}</h3><p>Create, orchestrate, monitor and scale AI-powered work from the same command plane.</p></article>)}</div></section>
      <section className="j-section" id="entertainment"><span className="j-eyebrow">ENTERTAINMENT DIVISION</span><h2>The J-ROC Entertainment Studio.</h2><p className="j-muted">Music, film, games, comics, publishing and media — built from the same platform, workers and factories.</p><div className="j-ent">{["🎵 Music","🎞 Film","🎮 Games","💥 Comics","📚 Publishing","📺 Media"].map(x=><div key={x}>{x}</div>)}</div></section>
      <section className="j-cta"><h2>The finished product is not a website.<br/>It is an operating system.</h2><p>Enter the J-ROC AI OS and command the workforce, divisions and factories.</p><a className="j-btn" href="/os">Enter J-ROC AI →</a></section>
    </main>
    <footer className="j-footer">© {new Date().getFullYear()} J-ROC AI · jrocai.online · Chairman Jesse</footer>
    <style jsx global>{`
      .jroc-front{min-height:100vh;background:#05080f;color:#e9eefb;overflow:hidden;font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.jroc-front a{text-decoration:none;color:inherit}
      .j-grid{position:fixed;inset:0;z-index:0;pointer-events:none;background-image:linear-gradient(rgba(79,140,255,.055) 1px,transparent 1px),linear-gradient(90deg,rgba(79,140,255,.055) 1px,transparent 1px);background-size:56px 56px}.j-aurora{position:fixed;inset:-20% -10% auto;height:80vh;z-index:0;pointer-events:none;background:radial-gradient(600px 420px at 18% 12%,rgba(79,140,255,.22),transparent 60%),radial-gradient(560px 460px at 82% 8%,rgba(124,92,255,.2),transparent 60%);filter:blur(10px)}
      .j-nav{position:fixed;z-index:20;top:0;left:0;right:0;padding:14px clamp(16px,4vw,44px);display:flex;align-items:center;gap:22px;background:rgba(5,8,15,.76);backdrop-filter:blur(14px);border-bottom:1px solid #1e2b45}.j-brand{display:flex;align-items:center;gap:10px;font-weight:800}.j-brand b{color:#4f8cff}.j-logo{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;color:#04101f;background:linear-gradient(135deg,#4f8cff,#7c5cff);font-size:13px}.j-nav nav{display:flex;gap:22px;margin-left:auto;color:#8ea3c4;font-size:14px}.j-nav nav a:hover{color:white}.j-btn{display:inline-flex;align-items:center;justify-content:center;padding:12px 19px;border-radius:12px;background:linear-gradient(135deg,#4f8cff,#7c5cff);color:#04101f!important;font-weight:700;box-shadow:0 10px 30px rgba(79,140,255,.25)}.j-ghost{background:rgba(255,255,255,.04);color:#e9eefb!important;border:1px solid #1e2b45;box-shadow:none}
      .jroc-front main{position:relative;z-index:1;max-width:1180px;margin:auto;padding:0 clamp(16px,4vw,44px)}.j-hero{min-height:100vh;padding-top:130px;display:grid;grid-template-columns:1.05fr .95fr;gap:40px;align-items:center}.j-eyebrow{font-size:12px;letter-spacing:.18em;text-transform:uppercase;color:#4f8cff;font-weight:800}.j-hero h1{font-size:clamp(40px,6vw,74px);line-height:1.04;letter-spacing:-.04em;margin:15px 0 24px}.j-hero h1 span{background:linear-gradient(100deg,#4f8cff,#7c5cff,#38bdf8);-webkit-background-clip:text;color:transparent}.j-hero p,.j-muted{color:#8ea3c4;font-size:17px;max-width:700px;line-height:1.7}.j-hero p b{color:#dbe6fb}.j-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.j-live{display:inline-flex;gap:9px;align-items:center;margin-top:24px;padding:9px 15px;border:1px solid #1e2b45;border-radius:999px;color:#8ea3c4;font-size:13px;background:rgba(16,24,42,.66)}.j-live i{width:9px;height:9px;border-radius:50%;background:#34d399;box-shadow:0 0 0 4px rgba(52,211,153,.15)}
      .j-core{width:min(420px,80vw);aspect-ratio:1;position:relative;display:grid;place-items:center;margin:auto}.j-ring{position:absolute;inset:0;border:1px solid rgba(79,140,255,.28);border-radius:50%;animation:jspin 26s linear infinite}.j-ring.r2{inset:16%;animation-duration:20s;animation-direction:reverse;border-color:rgba(124,92,255,.32)}.j-ring.r3{inset:32%;animation-duration:15s;border-color:rgba(56,189,248,.3)}@keyframes jspin{to{transform:rotate(360deg)}}.j-corecenter{width:44%;aspect-ratio:1;border-radius:50%;display:grid;place-items:center;text-align:center;background:radial-gradient(circle at 35% 30%,rgba(79,140,255,.5),rgba(124,92,255,.2) 45%,rgba(5,8,15,.9) 72%);border:1px solid rgba(79,140,255,.5);box-shadow:0 0 70px rgba(79,140,255,.35),inset 0 0 50px rgba(79,140,255,.2);letter-spacing:.18em}.j-corecenter b{font-size:22px}.j-core label{position:absolute;bottom:-20px;font-size:10px;color:#8ea3c4;letter-spacing:.12em}
      .j-stats{position:relative;z-index:1;display:grid;grid-template-columns:repeat(5,1fr);gap:12px;border-block:1px solid #1e2b45;padding:30px 0}.j-stats div{text-align:center}.j-stats b{display:block;font-size:40px;background:linear-gradient(100deg,#fff,#9db8ff);-webkit-background-clip:text;color:transparent}.j-stats small{color:#8ea3c4;text-transform:uppercase;letter-spacing:.12em;font-size:11px}
      .j-section{padding:110px 0}.j-section h2{font-size:clamp(30px,4.5vw,54px);line-height:1.05;margin:12px 0 16px;letter-spacing:-.04em}.j-gridcards,.j-solutions{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:42px}.j-gridcards article,.j-solutions article,.j-execs article,.j-divisions article,.j-ent div{padding:20px;border:1px solid #1e2b45;border-radius:18px;background:rgba(16,24,42,.66);transition:.2s}.j-gridcards article:hover,.j-solutions article:hover,.j-divisions article:hover{transform:translateY(-3px);border-color:rgba(79,140,255,.5)}.j-gridcards article{display:flex;gap:15px}.j-gridcards strong{font-size:24px}.j-gridcards b{font-size:16px}.j-gridcards p,.j-solutions p{margin-top:5px;color:#8ea3c4;font-size:14px}.j-execs{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:38px}.j-execs article{text-align:center}.j-execs b{display:block;font-size:21px;color:#4f8cff}.j-execs span{color:#8ea3c4;font-size:13px}.j-ceo{display:flex;gap:18px;align-items:center;margin-top:16px;padding:22px;border:1px solid rgba(79,140,255,.28);border-radius:18px;background:rgba(79,140,255,.08)}.j-ceo>span{font-size:38px}.j-ceo p{color:#8ea3c4;margin-top:5px}.j-divisions{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:40px}.j-divisions span{display:block;font-size:26px;margin-bottom:8px}.j-divisions b{font-size:14px}.j-solutions{grid-template-columns:repeat(3,1fr)}.j-solutions h3{margin-bottom:8px}.j-ent{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:38px}.j-ent div{font-weight:700}.j-cta{text-align:center;padding:90px 20px;margin:20px 0 80px;border:1px solid #1e2b45;border-radius:26px;background:radial-gradient(700px 340px at 50% 0%,rgba(79,140,255,.16),transparent 70%)}.j-cta h2{font-size:clamp(28px,4vw,48px);line-height:1.05}.j-cta p{color:#8ea3c4;margin:18px 0 28px}.j-footer{position:relative;z-index:1;border-top:1px solid #1e2b45;padding:38px 16px;text-align:center;color:#8ea3c4;font-size:13px}
      @media(max-width:900px){.j-nav nav{display:none}.j-hero{grid-template-columns:1fr;text-align:center}.j-hero p{margin:auto}.j-actions,.j-live{justify-content:center}.j-core{order:-1}.j-gridcards,.j-solutions,.j-ent{grid-template-columns:1fr 1fr}.j-divisions{grid-template-columns:repeat(3,1fr)}.j-execs{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.j-stats{grid-template-columns:repeat(2,1fr)}.j-gridcards,.j-solutions,.j-ent,.j-divisions,.j-execs{grid-template-columns:1fr}.j-nav .j-btn{display:none}}
    `}</style>
  </div>;
}
